default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.database[:user] %>
  password: <%= Rails.application.credentials.database[:password] %>

development:
  <<: *default
  database: lemoney_development

test:
  <<: *default
  database: lemoney_test

production:
  <<: *default
  database: lemoney_production
